### ISSUE TITLE
List files with a short name

### ISSUE THREAD

**Issue by senditsai** [jenkinsci/maven-artifact-choicelistprovider-plugin#13]
Currently, there are show full information of artifacts name, include base URL, and repository, In fact, is unnecessary.

In my opinion, Only shown maven-code-coverage-1.0.war is better

![image](https://user-images.githubusercontent.com/78411440/109776370-756f2680-7c3d-11eb-9708-bf867b96aa7b.png)

**Comment by phreakadelle** [comment]
Yes, this would be easier to read. Unfortunately the base plugin does not support it. I have raised it years ago:
* https://issues.jenkins.io/browse/JENKINS-22317
