### ISSUE TITLE
How to setup in a declarative or scripted pipeline

### ISSUE THREAD

**Issue by luisalves00** [jenkinsci/maven-artifact-choicelistprovider-plugin#15]
Hi,

The plugin works fine on the jenkins UI, but didn't figure out how can a use it in a declarative pipeline, or even in a scripted one.
Is there an example, or that is not possible at all?

Only found [this question](https://stackoverflow.com/questions/42392247/how-can-i-use-the-extended-choice-parameter-plugin-in-a-jenkins-pipeline-script) but seems to be a fork of the plugin and did not help a lot.

thanks

**Comment by luisalves00** [comment]
I came up with:

```groovy
properties ([
    parameters([ 
        [$class: 'ExtensibleChoiceParameterDefinition', 
             name: 'VERSION', 
             description: 'Microservice version',
             choiceListProvider: [
                $class: 'Nexus3ChoiceListProvider',
                url: 'http://nexus01.tagus.pt', 
                groupId: 'pt.tagus.core',
                artifactId: 'pt-core-boot',
                packaging: 'jar',
                classifier: 'boot',
                filterExpression: '^((?!SNAPSHOT).)*$',
                reverseOrder: true
             ]
         ]          
    ])
])
```

but the combo box is not populated. It works on the configuration page and can fetch the artifacts. Any idea why?

**Comment by luisalves00** [comment]
As an workaround if I go to configure tab and just save (bit anoying), the combo box starts working :)

**Comment by luisalves00** [comment]
After asking help from a quite experienced colleague, it seems we need to provide all fields in the constructor for it to work:

```groovy
[$class: 'ExtensibleChoiceParameterDefinition', 
             name: 'microservice_version', 
             description: 'Microservice version',
             editableType: 'NoFilter',
             choiceListProvider: [
                $class: 'Nexus3ChoiceListProvider',
                url: 'http://nexus01.tagus.pt', 
                groupId: 'pt.tagus.core',
                artifactId: 'pt-core-boot',
                packaging: 'jar',
                credentialsId: '',
                repositoryId: '',
                classifier: 'boot',
                filterExpression: '^((?!SNAPSHOT).)*$',
                reverseOrder: true
            ]
        ]    
```

**Comment by phreakadelle** [comment]
Nice :)

**Comment by phreakadelle** [comment]
Limiting the number of results is an interesting thing. But as the plugin is growing at the moment i am afraid we get too many options. We already have two additional ones for the REGEX part (to filter the artifacts after the search) and to inverse it. Now there is then the next one for limiting the result. I am not saying its a bad idea but i need to find a nice and handy way for it as just limiting it would not help as we still rely on the return-order of the nexus. So you might not get automatically the latest results.. 

Displaying only the artifact name is not possible. I would like to have it as well, but the base plugin "Extensible Choice Plugin" does not have an option for it.

**Comment by luisalves00** [comment]
The displaying limitation is not a big deal, as I can extract the version with REGEX afterwards, but limiting the number of results is going to be really required after a while, unless we start dropping artifacts from nexus to keep the selection small. We plan to release often, so the selection will quickly grow a lot.

**Comment by phreakadelle** [comment]
At least the Lucene interface does provide a "count" parameter which can be used.
* https://repository.sonatype.org/nexus-indexer-lucene-plugin/default/docs/path__lucene_search.html

**Comment by luisalves00** [comment]
On nexus3 it seems to be decided by the server, so you cannot control it, but you can truncate the records for the number configured by the user (client side "pagination").
