### ISSUE TITLE
Semantic versioning sorting on Nexus3ChoiceListProvider

### ISSUE THREAD

**Issue by luisalves00** [jenkinsci/maven-artifact-choicelistprovider-plugin#16]
The Nexus3ChoiceListProvider don't sort as expected, i.e. latest version first.

### Results

Expected result:

http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.10.1/artifact-boot-1.10.1-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.10.0/artifact-boot-1.10.0-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.9.2/artifact-boot-1.9.2-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.9.1/artifact-boot-1.9.1-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.9.0/artifact-boot-1.9.0-boot.jar

Actual result:

http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.9.2/artifact-boot-1.9.2-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.9.1/artifact-boot-1.9.1-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.9.0/artifact-boot-1.9.0-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.10.1/artifact-boot-1.10.1-boot.jar
http://nexus.tagus.pt/repository/maven-releases/me/core/artifact-boot/1.10.0/artifact-boot-1.10.0-boot.jar

**Comment by phreakadelle** [comment]
Hey @luisalves00, maybe you can try on your Nexus3 instance to call the REST API directly to verify that the output is as expected

https://server/service/local/lucene/search?p=<packaging>&a=<artifact>&g=<group>&repositoryId=<repo>&sort=version

**Comment by phreakadelle** [comment]
My fault, my link was wrong. The link you have posted is for the Nexus2 interface, which only has the count. Right.

The Nexus3 search-asset API has the sort parameter in:
* https://help.sonatype.com/repomanager3/rest-and-integration-api/search-api#SearchAPI-SearchAssets

I have verified on our Nexus3 that it works as expected. I will change the plugin and add the default sort by version

**Comment by luisalves00** [comment]
Great :), do you plan to release soon?

**Comment by luisalves00** [comment]
Wow, that's great. Thanks
