### ISSUE TITLE
Extended choice parameter - Nexus3 Artifact Choice Parameter, Working, but no Entries found

### ISSUE THREAD

**Issue by showaid** [jenkinsci/maven-artifact-choicelistprovider-plugin#8]
We recently upgrade nexus repository and Maven Artifact ChoiceListProvider (Nexus)  plugin altogether. 

Nexus Repository version is 3.29.2-02 and Maven Artifact ChoiceListProvider (Nexus) plugin version is 1.6.2. 

No entries found since then.

Relevant log looks as below:

```
2021-02-02 08:11:30.113+0000 [id=78]    INFO    o.j.p.m.n.Nexus3RestApiSearchService#callService: URI: https://nexus.example.com/service/rest/v1/search/assets?repository=%5Bmaven-releases%5D&group=%5Bcom.example%5D
2021-02-02 08:11:30.141+0000 [id=78]    INFO    o.j.p.m.n.Nexus3RestApiSearchService#callService: response from Nexus3 does not contain any results.
```

I am not sure but the encoded characters(e.g. %5B) are the cause.
When I try the URI in a browser, response is empty:
* https://nexus.example.com/service/rest/v1/search/assets?repository=%5Bmaven-releases%5D&group=%5Bcom.example%5D
```
{
  "items" : [ ],
  "continuationToken" : null
}
```

When I delete the encoded characters and try it again, response is not empty:
* https://nexus.example.com/service/rest/v1/search/assets?repository=maven-releases&group=com.example
``` 
{
  "items" : [ {
    "downloadUrl" : "https://nexus.example.com/repository/maven-releases/com/example/auth/1.0.1/auth-1.0.1.jar",
    "path" : "com/example/auth/1.0.1/auth-1.0.1.jar",
    "id" : "bWF2ZW4tY2x0LXJlbGVhc2VzOjcxYWZlYTU0MGUyM2RkZTVmYmFkYjQ5Y2JlOWU4MDJj",
    "repository" : "maven-releases",
    "format" : "maven2",
   ...
```

I am not sure if it's a problem of Nexus or the plugin, but please take a look.

**Comment by tibortru** [comment]
I just tried it on my Nexus Repository version is 3.28.1-01 and Maven Artifact ChoiceListProvider (Nexus) plugin version is 1.6.2. and also same message appears "Working but no entries found" :(

**Comment by phreakadelle** [comment]
Guys, we did a couple of merges of PRs in the last days. So you are saying it worked before and its not working now?

**Comment by showaid** [comment]
Hello,

Precisely speaking, my environment was as below:

* Nexus : 3.16.2-01
* Maven Artifact ChoiceListProvider (Nexus) plugin : 1.5.1

This combination worked fine.

I upgraded the Nexus(from 3.16.2-01 to 3.29.2-02) first. The plugin didn't work since then.

Relevant error log was as below:
```
2021-02-01 00:06:02.595+0000 [id=81211] WARNING o.j.p.m.n.Nexus3RestApiSearchService#callService: failed to map
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "contentType" (class org.jenkinsci.plugins.maven_artifact_choicelistprovider.nexus3.Item), not marked as ignorable (6 known properties: "checksum", "path", "downloadUrl", "repository", "id", "format"])
```

I thought it might be a problem of plugin version, so I update the plugin to 1.6.2. But it still doesn't work.

The encoded character is captured from Jenkins log file.
`
2021-02-02 08:11:30.113+0000 [id=78]    INFO    o.j.p.m.n.Nexus3RestApiSearchService#callService: URI: https://nexus.example.com/service/rest/v1/search/assets?repository=%5Bmaven-releases%5D&group=%5Bcom.example%5D
`

I don't know why Jenkins generates the URI like that.
Would it be a problem of combination of Jenkins and Plugin?
My Jenkins version is 2.200.

Thank you.

**Comment by phreakadelle** [comment]
Ok understodd, so even the old plugin 1.5.1 didnt work with Nexus 3.16.2-01 right? This means even downgrading the plugin back to 1.5.1 in Jenkins would not solve your problem, right?

I need some time for that to analyze it. Every PR is welcome.

**Comment by showaid** [comment]
@phreakadelle 

Let me summarize:

* Nexus 3.16.2-01 + Plug-in 1.5.1 -> worked fine
* Nexus 3.29.2-02 + Plug-in 1.5.1 -> didn't work (Unrecognized field "contentType" in Jenkins log)
* Nexus 3.29.2-02 + Plug-in 1.62 -> still doesn't work (abnormal URI?)

So, downgrading the plugin will not help.

Thank you.

**Comment by phreakadelle** [comment]
Ok. Thanks for clarification.

**Comment by coolpalani** [comment]
@phreakadelle 

This issue is still exist. We're also facing same issue and throwing an error message "(Working, but no Entries found)"
Nexus 3.30.0 + Plug-in 1.7.1

**Comment by phreakadelle** [comment]
Next week i will provide you a fix which will ignore unknown properties. 

https://stackoverflow.com/questions/4486787/jackson-with-json-unrecognized-field-not-marked-as-ignorable
